#! /bin/sh
#
# Based on example:
# https://github.com/baskerville/bspwm/blob/master/examples/bspwmrc

bspc config border_width 4
bspc config window_gap 0
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true

# Make desktop names and number keys align
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Make Java Swing applications spawn windows properly
wmname LG3D

bspc rule --add 'Emacs' 'state=tiled'

sxhkd &

# Start the panel!
(cd ~/.config/bspwm && exec ./panelinit) &

# Launch startup applications
(cd ~/.config/bspwm && exec ./startup) &
