#! /bin/sh
#
# Launch initial applications, and do non-DM tweaks

xrdb ~/.Xresources

# Initialize gnome-keyring
# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK

# Caps Lock acts as Esc when pressed by itself, and Ctrl with another key
setxkbmap -option 'ctrl:nocaps' &
xcape -e 'Control_L=Escape' &

# Place the wallpaper on a black background
xsetroot && feh --bg-center ~/Pictures/wallpaper.png

# Start startup applications
# dropbox &
dunst &
# gajim &
nm-applet &
numlockx &
redshift &
# rescuetime &
stalonetray &
