#! /bin/sh
#
# Based on example:
# https://github.com/baskerville/bspwm/blob/master/examples/bspwmrc

xrandr --output DP-1 --left-of eDP-1

bspc config border_width 4
bspc config split_ratio 0.5
bspc config window_gap 0

bspc config borderless_monocle true
bspc config click_to_focus true
bspc config gapless_monocle true

# 1, ..., 9, 0 so desktop names and number keys align
bspc monitor DP-1  -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 0

# Make Java Swing applications spawn windows properly
wmname LG3D

bspc rule -a Emacs state=tiled
bspc rule -a SpeedCrunch state=floating
bspc rule -a copyq state=floating

sxhkd &

# Start the panel!
(cd ~/.config/bspwm && exec ./panelinit) &

# Launch startup applications
(cd ~/.config/bspwm && exec ./startup) &
