#! /bin/sh
#
# Based on example:
# https://github.com/baskerville/bspwm/blob/master/examples/bspwmrc

bspc config border_width 4
bspc config split_ratio 0.5
bspc config window_gap 0

bspc config borderless_monocle true
bspc config click_to_focus true
bspc config gapless_monocle true

i=0
for monitor in "$(bspc query -M)"; do
  bspc monitor "$monitor" -d a b c d e
  (( ++i ))
done
unset i

# Make Java Swing applications spawn windows properly
wmname LG3D

bspc rule -a Emacs state=tiled
for app in antimicro copyq SpeedCrunch Steam; do
  bspc rule -a "$app" state=floating
done

sxhkd &

# Start the panel!
(cd ~/.config/bspwm && exec ./panelinit) &

# Launch startup applications
(cd ~/.config/bspwm && exec ./startup) &
