#!/bin/bash
#
# Various options read by panelinit and panelout

PANEL_IN_FIFO=/tmp/panel_in_fifo
PANEL_OUT_FIFO=/tmp/panel_out_fifo
PANEL_PID_LOC=/tmp/panel_pid

PANEL_FONT="Droid Sans Mono:size=10:antialias=true:hinting=true"
PANEL_GEOMETRY=+80  # 16x5
PANEL_HEIGHT=18

DESKTOP_FREE_COLOR=#AAAAAA
DESKTOP_URGENT_COLOR=#00AAAA
SEPARATOR_COLOR=$DESKTOP_FREE_COLOR

BAT_SYS_PATH=/sys/class/power_supply/BAT0/
