#!/bin/bash
#
# Launch initial applications, and do non-DM tweaks

wait_for_net() {
  while [[ ! $(ping -c 1 8.8.8.8) ]]; do
    sleep 1
  done
}

xmodmap ~/.Xmodmap
xrdb ~/.Xresources

# Caps Lock acts as Esc when pressed by itself, and Ctrl with another key
xcape -e 'Control_R=Escape' &

# Place the wallpaper on a black background
xsetroot && feh --bg-center ~/cloud/wallpaper.png

# Set up lock script
xss-lock physlock &

# Start startup applications
copyq &
numlockx &
redshift &
stalonetray &
nm-applet &

(wait_for_net && gajim) &
(wait_for_net && megasync) &
(wait_for_net && riot-web) &
