#!/bin/bash
#
# Launch initial applications, and do non-DM tweaks

xrdb ~/.Xresources

# Caps Lock acts as Esc when pressed by itself, and Ctrl with another key
setxkbmap -option 'ctrl:nocaps' &
xcape -e 'Control_L=Escape' &

# Place the wallpaper on a black background
xsetroot && feh --bg-center ~/Pictures/wallpaper.png

# Set up lock script
xss-lock physlock &

# Start startup applications
dropbox &
dunst &
(sleep 5 && gajim) &
nm-applet &
numlockx &
redshift &
stalonetray &
