#!/bin/sh
#
# Build a statusline from stdin; output should be piped to lemonbar

# If the string is longer than the given length, shorten it and end it with ...
dottruncate() {
  maxlen=$1; shift

  string=$@
  len=${#string}

  if [ $len -ge $maxlen ]; then
    echo -n $(echo $string | head -c $(expr $maxlen - 3))
    echo -n '...'
  else
    echo -n $string
  fi
}

set -euo pipefail

. ./panelopts

curbattery=?
curclock=?
curdesktop=?
curwindow=?

while read -r line; do
  case $line in
    B*)
      curbattery=${line#?}
      ;;
    C*)
      curclock=${line#?}
      ;;
    T*)
      curwindow=${line#?}
      ;;
    WM*)
      IFS=:
      curdesktop=""
      for desktop in {$line#??}; do
        case $desktop in
          f*) # Unoccupied desktop, unfocused
            curdesktop+=" %{F$DESKTOP_FREE_COLOR}${desktop#?}%{F-}" ;;
          F*) # Unoccupied desktop, focused
            curdesktop+=" [%{F$DESKTOP_FREE_COLOR}${desktop#?}%{F-}]" ;;
          o*) # Occupied desktop, unfocused
            curdesktop+=" ${desktop#?}" ;;
          O*) # Occupied desktop, focused
            curdesktop+=" [${desktop#?}]" ;;
        esac
      done
      unset IFS
      ;;
  esac

  echo -n "%{l}$curdesktop"
  echo -n "%{c}$(dottruncate 120 $curwindow)"
  echo -n "%{r}Battery: $curbattery :: $curclock"
  echo
done
