#!/usr/bin/bash
#
# Start panelupdate, the forked processes feeding it, and lemonbar

cleanup() {
  # The \r hides the ^C that appears
  echo -e '\rPerforming cleanup...'

  bspc config top_padding 0
  # Avoid executing cleanup() again when I send the signal to kill myself
  trap - TERM
  # Kill myself and all my children
  kill 0
}

# Get the battery percentage from acpi
battery() {
  # If an argument is given, cut it instead
  echo ${1:-$(acpi -b)} | cut -d, -f 2 | tr --delete --complement '[:digit:]'
}

# Get the battery percentage and charging status at the same time
batterypretty() {
  rawinfo=$(acpi -b)
  percent=$(battery "$rawinfo")

  case "$(echo $rawinfo | cut -d' ' -f 3)" in
    'Discharging,') state='-' ;;
    'Charging,') state='+' ;;
    # Otherwise 'Full' or 'Unknown'; let state evaluate to the empty string
  esac

  echo $state$percent%
}

# Get the date and time
clock() {
  date "+%a %H:%M"
}

# Get the name of the currently focused desktop
curdesktop() {
  bspc query -D -d focused
}

# Get the name of the currently focused window
curwindow() {
  xdotool getwindowfocus getwindowname
}

# Repeatedly invoke the given command with the given frequency
wraprepeat() {
  # Number of seconds to wait between invocations
  interval=$1; shift
  # Format string to use
  format=$1; shift

  # The command to actually execute
  docmd=$@

  last='\n\n\n'

  while true; do
    result=$($docmd)

    if [ "$last" != "$result" ]; then
      printf "$format" "$result"
      last=$result
    fi

    sleep $interval
  done
}

# Do cleanup before exiting
trap cleanup INT TERM QUIT EXIT

. panelopts

# Initialize the fifo, removing it first if it already exists
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Feed various pieces of information into panelupdate
wraprepeat 1 'D%s\n' curdesktop > $PANEL_FIFO &
wraprepeat 2 'C%s\n' clock > $PANEL_FIFO &
wraprepeat 3 'B%s\n' batterypretty > $PANEL_FIFO &

xtitle -sf 'T%s' > $PANEL_FIFO &

# TODO: Add more desktop status info by parsing bspc subscribe
# bspc control --subscribe > "$PANEL_FIFO" &

# Make way for the panel!
bspc config top_padding $PANEL_HEIGHT

./panelout < $PANEL_FIFO | lemonbar -p -f "$PANEL_FONT" &

wait
