#!/bin/sh
#
# Build a statusline from stdin; output should be piped to lemonbar

# If the string is longer than the given length, shorten it and end it with ...
dottruncate() {
  maxlen=$1; shift

  string=$@
  len=${#string}

  if [ $len -ge $maxlen ]; then
    echo -n $(echo $string | head -c $(expr $maxlen - 3))
    echo -n '...'
  else
    echo -n $string
  fi
}

set -euo pipefail

curbattery=?
curclock=?
curdesktop=?
curwindow=?

while read -r line; do
  case $line in
    B*)
      curbattery=${line#?}
      ;;
    C*)
      curclock=${line#?}
      ;;
    D*)
      curdesktop=${line#?}
      ;;
    T*)
      curwindow=${line#?}
      ;;
  esac

  echo -n "%{l}Desktop: $curdesktop"
  echo -n "%{c}$(dottruncate 120 $curwindow)"
  echo -n "%{r}Battery: $curbattery :: $curclock"
  echo
done
